export const CitiesList = [
    {id:0,name:'قیطریه'},
    {id:1,name:'کاشانک'},
    {id:2,name:'ولیعصر'},
    {id:3,name:'ولنجک'},
    {id:4,name:'محمودیه'},
    {id:5,name:'دربند'},
    {id:6,name:'جماران'},
    {id:7,name:'دزاشیب'},
    {id:8,name:'نیاوران'},
    {id:9,name:'اراج'},
    {id:10,name:'چیذر'},
    {id:11,name:'حکمت'},
    {id:12,name:'ازگل'},
]
